apiVersion: v1
kind: Service
metadata:
  name: vodademo-proxy
  labels:
    service: vodademo-proxy
spec:
  type: NodePort
  selector:
    app: vodademo-proxy-app

  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: vodademoproxy
