apiVersion: v1
kind: Service
metadata:
  name: vodademo
  labels:
    service: vodademo
spec:
  type: NodePort
  selector:
    app: vodademo-app
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: vodademo
